<?php

namespace ContainerPBgpyRB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InterestController' shared autowired service.
     *
     * @return \App\Controller\InterestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InterestController.php';

        $container->services['App\\Controller\\InterestController'] = $instance = new \App\Controller\InterestController(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\InterestController', $container));

        return $instance;
    }
}
