<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPBgpyRB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPBgpyRB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPBgpyRB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPBgpyRB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPBgpyRB\App_KernelDevDebugContainer([
    'container.build_hash' => 'PBgpyRB',
    'container.build_id' => '5fb7ddfd',
    'container.build_time' => 1714126176,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPBgpyRB');
