<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIosjPxA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIosjPxA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIosjPxA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIosjPxA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIosjPxA\App_KernelDevDebugContainer([
    'container.build_hash' => 'IosjPxA',
    'container.build_id' => '7307ba96',
    'container.build_time' => 1713350176,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIosjPxA');
